name: 'Flask Issue Management'
on:
  issues:
    types: [opened, edited, deleted, closed, reopened, assigned, labeled, milestoned]
  issue_comment:
    types: [deleted]

permissions: 
  contents: read
  issues: write
  repository-projects: read

jobs:
  issue-fields-validator:
    name: Issue Fields Validation
    uses: bitcot/aiqa/.github/workflows/issue_fields_validator.yml@v4.0.5
    with:
      branch: v4.0.5
    secrets:
      GH_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  sub-issue-fields-validator:
    name: Sub-Issue Validation
    uses: bitcot/aiqa/.github/workflows/sub_issue_fields_validator.yml@v4.0.5
