name: 'Issue workflow'
on:
  issues:
    types: [opened, edited, deleted, closed, reopened, assigned, labeled, milestoned]
  issue_comment:
    types: [deleted]

permissions: 
  contents: read  # Ensures access to the repository's contents (for read actions like checkout)
  issues: write   # Ensures write access to issues (if needed)
  repository-projects: read # If you need access to project boards (optional)

jobs:
  issue-fields-validator:
    name: QE

    uses: bitcot/aiqa/.github/workflows/issue_fields_validator.yml@v4.0.5
    with:
      branch: v4.0.5

    secrets:
      GH_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  
  sub-issue-fields-validator:
    name: QE
    uses: bitcot/aiqa/.github/workflows/sub_issue_fields_validator.yml@v4.0.5
