name: '[QE] Quality Engineering'
on:
  pull_request:
    branches:
      - main
      - master
      - dev
      - develop
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize  
      - closed
  push:
    branches:
      - main
      - master
      - dev
      - develop
      - feat/step4

permissions:
  contents: write 
  id-token: write  
  pull-requests: write   
  checks: write
  security-events: write

jobs:
  quality-engineering:
    name: Quality Checks
    uses: bitcot/aiqa/.github/workflows/quality-engineering.yml@v4.1.0
    with:
      danger: false
      nodeLint: false
      pythonFormat: true
      pythonLint: true
      sonar: false
      securityScan: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN || 'dummy' }}
      SONAR_HOST: ${{ secrets.SONAR_HOST || 'dummy' }}
      PROJECT_KEY: ${{ secrets.PROJECT_KEY || 'dummy' }}
      AWS_REGION: ${{secrets.AWS_REGION || 'us-east-1'}}
      TASK_DEFINITION_BUCKET: ${{secrets.TASK_DEFINITION_BUCKET || 'dummy'}}
