name: '[QE] Quality Engineering'
on:
  pull_request:
    branches:
      - main
      - master
      - dev
      - develop
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize  
      - closed
  push:
    branches:
      - main
      - master
      - dev
      - develop
      - feat/step4

permissions:
  contents: write 
  id-token: write  
  pull-requests: write   
  checks: write
  security-events: write

jobs:
  quality-engineering:
    name: Flask Quality Checks
    uses: bitcot/aiqa/.github/workflows/quality-engineering.yml@v4.1.0
    with:
      danger: true
      nodeLint: false
      pythonFormat: true
      pythonLint: true
      sonar: true
      securityScan: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}
      PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      AWS_REGION: ${{secrets.AWS_REGION}}
      TASK_DEFINITION_BUCKET: ${{secrets.TASK_DEFINITION_BUCKET}}
